### ISSUE TITLE
"Hide watched" в списке сериалов не скрывает просмотренные

### ISSUE THREAD

**Issue by eschava** [ufian/soap4me#1]
Думаю что достаточно добавить элемент
'PlayCount': 0 if (self.data.get('unwatched', 0) > 0) else 1,
к словарю meta в методе  SoapSerial.menu

**Comment by ufian** [comment]
А в какой версии Kodi такое поведение?

**Comment by eschava** [comment]
Kodi 16.1

**Comment by eschava** [comment]
Обнаружился баг
Если зайти в меню "Все сериалы", то с режимом "Hide watched" скрываются все сериалы, кроме тех, у которых есть непросмотренные серии. Все остальные (даже которые не смотрели) имеют галочку "просмотрено"

**Comment by eschava** [comment]
Пофиксил в своем бренче, но не могу создать реквест, пока не заапрувлен предыдущий
