### ISSUE TITLE
Иметь режим при выборе сериала показывать сразу список серий непросмотренного сезона если он один

### ISSUE THREAD

**Issue by eschava** [ufian/soap4me#2]

**Comment by eschava** [comment]
Моя попытка реализации

settings.xml

`<setting id="list_unwatched_season" type="bool" label="Открывать непросмотренный сезон" default="false" />`

addon.py
**SoapConfig.**init****
`self.list_unwatched_season = __addon__.getSetting('list_unwatched_season') == "true"`

**SoapEpisodes**

```
    def count_unwatched_seasons(self):
        return len(filter(self.is_unwatched_season, self.episodes))

    def first_unwatched_season(self):
        return next(s for s in self.seasons if self.is_unwatched_season(s))

    def is_unwatched_season(self, season):
        return not all(ep.is_watched() for ep in self.episodes[season].values())
```

**SoapApi.process**

```
        elif parts.page == 'Episodes':
            all_episodes = self.get_all_episodes(parts.sid)

            if parts.season is None:
                list_unwatched_season = self.config.list_unwatched_season
                if  all_episodes.count_seasons() > 1 and (not list_unwatched_season or all_episodes.count_unwatched_seasons() > 1):
                    rows = all_episodes.list_seasons()
                    if self.config.reverse:
                        rows = rows[::-1]
                    return rows
                parts.season = str(all_episodes.first_unwatched_season() if list_unwatched_season else all_episodes.first_season())

            rows = all_episodes.list_episodes(int(parts.season), self.config)
            if self.config.reverse:
                rows = rows[::-1]
            return rows
```

**Comment by ufian** [comment]
Освой механизм pull request, будет гораздо проще.

**Comment by eschava** [comment]
У меня с ним все в порядке :)
Посчитал что мой код слишком сырой чтобы напрямую предлагать патч

**Comment by ufian** [comment]
Pull-request предполагает возможность доработки. В любом случае будет удобнее.

**Comment by eschava** [comment]
ок, подготовлю

**Comment by ufian** [comment]
На всякий случай: твои идеи хорошие, не бойся "плохой" код предлагать. Если что я поправлю, при этом твой вклад останется в истории.

**Comment by eschava** [comment]
Ваша версия делает не совсем то, что я описал в этой задаче
Хотелось бы чтобы автоматически открывался непросмотренный сезон, только если он такой один
А ваша версия всегда открывает первый непросмотренный
И теряется возможность посмотреть список оставшихся сезонов
С какой-то стороны это даже удобнее, но все-таки по-другому :)

**Comment by ufian** [comment]
Я тебя понял, давай поправим.
