### ISSUE TITLE
Скрывать просмотренные сериалы в "Мои сериалы"

### ISSUE THREAD

**Issue by Immelstorn** [ufian/soap4me#7]
Было бы неплохо в "Моих сериалах" не вываливать все 100500 которые уже давно посмотрел, а показывать только те, у кого есть новые серии

**Comment by ufian** [comment]
В 16 Kodi можно было встроенными фильтрами выбрать, чтобы показывалось только непросмотренное.

**Comment by Immelstorn** [comment]
В Kodi 17 такой опции в аддонах нет

**Comment by swapper9** [comment]
Можно ли добавить разделение, как на сайте, на отдельные группы?
1. с новыми эпизодами
2. просмотренные
3. просмотренные, сериал закончен

**Comment by ufian** [comment]
Сделал группу "с новыми эпизодами"

**Comment by Immelstorn** [comment]
Спасибо! Не знаю, связано ли это с последними изменениями, но серии перестали помечаться просмотренными.

**Comment by darkwebdev** [comment]
> Спасибо! Не знаю, связано ли это с последними изменениями, но серии перестали помечаться просмотренными.

Тоже такое заметил, после последнего апдейта иногда не отмечает просмотренные.

**Comment by darkwebdev** [comment]
@Immelstorn Репозиторий аддона обновлен до v1.0.19, можно тестить на своем устройстве и закрывать issue, если все работает.
